create table if not exists public.user_seed_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null,
  article_title text not null,
  category text not null check (category in ('경제', '과학', '사회', '국제', '환경', '문화', '스포츠', '기술', '동물', '우주')),
  source_url text not null,
  completed_at timestamptz not null,
  completed_on date not null,
  xp_earned integer not null default 0 check (xp_earned >= 0),
  quiz_completed boolean not null default false,
  kid_article_cache_key text references public.kid_article_cache(cache_key) on delete set null,
  article_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_seed_records_user_article_day_key unique (user_id, article_id, completed_on)
);

create index if not exists user_seed_records_user_completed_at_idx
  on public.user_seed_records (user_id, completed_at desc);

alter table public.user_seed_records enable row level security;

grant select, insert, update on public.user_seed_records to authenticated;
grant usage, select on sequence public.user_seed_records_id_seq to authenticated;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_seed_records' and policyname = 'Users can read their own seed records') then
    create policy "Users can read their own seed records" on public.user_seed_records for select using (auth.uid() = user_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_seed_records' and policyname = 'Users can insert their own seed records') then
    create policy "Users can insert their own seed records" on public.user_seed_records for insert with check (auth.uid() = user_id);
  end if;
end $$;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'user_seed_records' and policyname = 'Users can update their own seed records') then
    create policy "Users can update their own seed records" on public.user_seed_records for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
  end if;
end $$;
